### ISSUE TITLE
Implement inventory management logic from gameplan

### ISSUE THREAD

**Issue by davidkpiano** [ianphil/spike-inventory-de#9]
### Description
As a developer, I would like to ensure that the business logic outlined in [the gamemplan doc](https://github.com/ianphil/spike-inventory-de/blob/master/docs/gameplan.md) is implemented.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Should be able to demonstrate a realistic simulation of aggregated inventory count for stores based on inventory events

### Resources
*Technical Design Document*
https://github.com/ianphil/spike-inventory-de/blob/master/docs/gameplan.md

### Tasks

- [x] Implement logic and constraints found in gameplan doc
- [x] Demonstrate with sample simulation (in the form of a test or otherwise)

**Comment by ianphil** [comment]
I think we should add a couple of items to the game plan.

1. The collections are static.
2. The store id is a property.
3. Example data schema for: S, D, H, L collections
